### ISSUE TITLE
small cap not recognize

### ISSUE THREAD

**Issue by GuyHedelin** [u-fischer/luaotfload#80] opened 2019-08-08 19:05 UTC
Hi,
Since the last update in July I get the following message:

Font shape `TU/TeXGyreSchola(0)/m/sc' undefined
(Font)              using `TU/TeXGyreSchola(0)/m/n' instead

When I run the same code with XeTeX all is as expected.

The minimal code is:

\documentclass{article}
\usepackage{fontspec}
\setmainfont{TeX Gyre Schola}
\begin{document}
italic: \textit{Gh}\\
slanted: \textsl{Gh}\\
bold: \textbf{Gh}\\
small cap: \textsc{Gh} 
\end{document}

When I look at the log, the difference is that the small caps are not loaded (cf. log excerpt)

luaotfload | cache : Lookup cache loaded from C:/Users/guy/AppData/Local/MiKTeX/
2.9/luatex-cache/generic/names/luaotfload-lookup-cache.luc.
luaotfload | aux : no font with id -1
luaotfload | aux : no font with id -1
luaotfload | aux : no font with id -1
luaotfload | aux : no font with id -1

Package fontspec Info: Font family 'TeXGyreSchola(0)' created for font 'TeX
(fontspec)             Gyre Schola' with options [Ligatures=TeX].
(fontspec)              
(fontspec)              This font family consists of the following NFSS
(fontspec)             series/shapes:
(fontspec)              
(fontspec)             - 'normal' (m/n) with NFSS spec.:
(fontspec)             <->"TeXGyreSchola:mode=node;script=latn;language=DFLT;+tl
ig;"
(fontspec)             - 'small caps'  (m/sc) with NFSS spec.: 
(fontspec)             - 'bold' (bx/n) with NFSS spec.:
(fontspec)             <->"TeXGyreSchola/B:mode=node;script=latn;language=DFLT;+
tlig;"
(fontspec)             - 'bold small caps'  (bx/sc) with NFSS spec.: 
(fontspec)             - 'italic' (m/it) with NFSS spec.:
(fontspec)             <->"TeXGyreSchola/I:mode=node;script=latn;language=DFLT;+
tlig;"
(fontspec)             - 'italic small caps'  (m/itsc) with NFSS spec.: 
(fontspec)             - 'bold italic' (bx/it) with NFSS spec.:
(fontspec)             <->"TeXGyreSchola/BI:mode=node;script=latn;language=DFLT;
+tlig;"
(fontspec)             - 'bold italic small caps'  (bx/itsc) with NFSS spec.: 

LaTeX Info: Redefining \rmfamily on input line 4.
 (./minimal.aux)

to compare with the same log excerpt with XeTeX:

Package fontspec Info: Font family 'TeXGyreSchola(0)' created for font 'TeX
(fontspec)             Gyre Schola' with options [Ligatures=TeX].
(fontspec)              
(fontspec)              This font family consists of the following NFSS
(fontspec)             series/shapes:
(fontspec)              
(fontspec)             - 'normal' (m/n) with NFSS spec.: <->"TeX Gyre
(fontspec)             Schola/OT:script=latn;language=DFLT;mapping=tex-text;"
(fontspec)             - 'small caps'  (m/sc) with NFSS spec.: <->"TeX Gyre
(fontspec)             Schola/OT:script=latn;language=DFLT;+smcp;mapping=tex-text;"
(fontspec)             - 'bold' (bx/n) with NFSS spec.: <->"TeX Gyre
(fontspec)             Schola/B/OT:script=latn;language=DFLT;mapping=tex-text;"
(fontspec)             - 'bold small caps'  (bx/sc) with NFSS spec.: <->"TeX
(fontspec)             Gyre
(fontspec)             Schola/B/OT:script=latn;language=DFLT;+smcp;mapping=tex-text;"
(fontspec)             - 'italic' (m/it) with NFSS spec.: <->"TeX Gyre
(fontspec)             Schola/I/OT:script=latn;language=DFLT;mapping=tex-text;"
(fontspec)             - 'italic small caps'  (m/itsc) with NFSS spec.:
(fontspec)             <->"TeX Gyre
(fontspec)             Schola/I/OT:script=latn;language=DFLT;+smcp;mapping=tex-text;"
(fontspec)             - 'bold italic' (bx/it) with NFSS spec.: <->"TeX Gyre
(fontspec)             Schola/BI/OT:script=latn;language=DFLT;mapping=tex-text;"
(fontspec)             - 'bold italic small caps'  (bx/itsc) with NFSS spec.:
(fontspec)             <->"TeX Gyre
(fontspec)             Schola/BI/OT:script=latn;language=DFLT;+smcp;mapping=tex-text;"

LaTeX Info: Redefining \rmfamily on input line 4.
 (minimal.aux)

I use MikTeX and the otf files used are the same. So has anybody an idea where is the problem?

Thanks

**Comment by u-fischer** [comment] 2019-08-08 19:59
I can reproduce it:. On miktex small caps are not recognized (but can be forced with +smcp). On texlive there is no problem. The only obvious difference I can see is that miktex has a slightly newer luatex (1.10.1) but I don't know if it is the source of the problem.

**Comment by zauguin** [comment] 2019-08-08 21:22
@u-fischer Can you upload `$TEXMF_VAR/luatex-cache/generic/fonts/otl/texgyreschola-regular.lua` please?

**Comment by u-fischer** [comment] 2019-08-08 21:31
[texgyreschola-regular.txt](https://github.com/u-fischer/luaotfload/files/3483769/texgyreschola-regular.txt)


@zauguin I guess you want the miktex one. I attach it as txt. I checked against the one from texlive and apart from the path and the time at the end, they are identical.

**Comment by zauguin** [comment] 2019-08-08 21:55
@u-fischer Right, thanks. I can not reproduce this with the current experimental version and looking at the differences between 1.10.0 and 1.10.1 I do not see anything which could cause this. So I do not think the engine is responsible. But I still have no idea where this is coming from.

**Comment by u-fischer** [comment] 2019-08-08 22:00
@zauguin  it is too late now, perhaps I have an idea tomorrow. I don't think that it the files or fonts, I attached the texlive tree and it still fails. So it is either something in the engine, or there is something additional in the miktex tree, or something else ;-).

**Comment by u-fischer** [comment] 2019-08-09 08:17
@zauguin it is rather curious. I made a trace and compared the code and in miktex commands associated to fonts are in many places in the log replace by empty commands. E.g. if the call looks like this:

~~~~
\str_if_eq:eeTF {\__fontspec_primitive_font_get_name:N \l__fontspec_tmpa_font }
                       {\__fontspec_primitive_font_get_name:N \l__fontspec_tmpb_font }
~~~~

the execution then does this argument assignment:

~~~~
#1<-\__fontspec_primitive_font_get_name:N \
#2<-\__fontspec_primitive_font_get_name:N \l__fontspec_tmpb_font 
~~~~

and this is in many places, e.g. texlive has ``\l__fontspec_fontface_cs_tl ->\l_fontspec_font`` but miktex 
``\l__fontspec_fontface_cs_tl ->\ ``.

It seems then to break at the smcp when lua gets an empty argument:

~~~~
\lua_now:e #1->\__lua_now:n {#1}
#1<-fontspec.check_ot_feat("\l__fontspec_tmp_tl ","smcp","\l__fontspec_lang_tl 
","\l__fontspec_script_tl ")

\l__fontspec_tmp_tl ->

\l__fontspec_lang_tl ->DFLT

\l__fontspec_script_tl ->latn
luaotfload | aux : no font with id -1
~~~~

In texlive this looks like this:

~~~~
\lua_now:e #1->\__lua_now:n {#1}
#1<-fontspec.check_ot_feat("\l__fontspec_tmp_tl ","smcp","\l__fontspec_lang_tl 
","\l__fontspec_script_tl ")

\l__fontspec_tmp_tl ->l_fontspec_font

\l__fontspec_lang_tl ->DFLT

\l__fontspec_script_tl ->latn
luaotfload | aux : font no 29 (nil) does not define feature smcp for script latn
 with language dflt
luaotfload | aux : no font with id 29
~~~~

(I made the test with latin modern not texgyre)

**Comment by GuyHedelin** [comment] 2019-08-09 09:54
@u-fischer and @zauguin As luaotfload and luatex have been updated at the same time in MikTeX I can't say which part is producing the problem. Before this update all was alright (if I remember, but I'm not sure, MikTeX used luaTeX 1.10.0).

@u-fischer I tried to force the small caps as you wrote but I can only do that localy with \fonspec{texgyreschola-regular.otf}[RawFeature=+smcp]. I tried to do it globaly in the preamble with \setmainfont but I didn't succeed. Do you know how to do it?

**Comment by u-fischer** [comment] 2019-08-09 14:06
@zauguin I think that at the core of the problem is this difference between miktex and texlive:

~~~~
\input luaotfload.sty
\font\testA="cmr10" at 9.99997pt\relax
\testA
\show\testA

\font\testB="cmr12" at 9.99997pt\relax
\font\testB="cmr12" at 9.99997pt\relax
\testB
\show\testB

\bye
~~~~

## output with texlive

~~~~
> \testA=select font cmr10 at 9.99997pt.
l.34 \show\testA
              
? 
> \testB=select font cmr12 at 9.99997pt.
l.39 \show\testB

~~~~

## output with miktex

~~~~
> \testA=select font cmr10 at 9.99997pt.
l.34 \show\testA
              
? 
! Undefined control sequence.
l.38 \testB
~~~~

so the luatex in miktex doesn't like it if a font is defined twice ...

loading luaotfload is necessary, without it works, so it is not the primitive font command.

**Comment by zauguin** [comment] 2019-08-09 15:17
@u-fischer That's odd. I mean I would completely see how a bug might make \testB load \nullfont or how this could trigger an error, but silently setting it to undefined?

Does this also happen with

```
[...]
\font\testB="cmr12" at 9.99997pt\relax
\font\testC="cmr12" at 9.99997pt\relax
\testB
\show\testB
\bye
```
or with
```
[...]
\font\testB="cmr12" at 9.99997pt\relax
\font\testB="cmr12" at 9pt\relax
\testB
\show\testB
\bye
```
?

**Comment by u-fischer** [comment] 2019-08-09 16:04
@zauguin both cases works fine, one only get the error if the font is used with the same command and same size - if one add 1sp it behaves again. 

And I just realized that I can get 1.10.1 with w32tex.org by using the luatex-dev version - and with it I get the problem too. So it looks as if this luatex version has a bug.

**Comment by zauguin** [comment] 2019-08-09 16:14
Right, I just found two commits in LuaTeX experimental, "patch for font overflow (HH)" (rev.  7137) and "fixed patch for font overflow to avoid deleting a csname" (rev. 7141), which introduce and fix this problem. Sadly, 10.10.1 has been released in between.

**Comment by u-fischer** [comment] 2019-08-09 16:19
@zauguin I will add an issue for miktex so that it reverts the binary. Not much one can do.

**Closed** 2019-08-09 17:09 UTC
