### ISSUE TITLE
Version 49978 in TeXLive 2018 causes fontspec to not work properly

### ISSUE THREAD

**Issue by svitalsky** [u-fischer/luaotfload#38] opened 2019-02-10 17:50 UTC
See here: https://tex.stackexchange.com/questions/474046/is-luaotfload-package-broken

**Comment by zauguin** [comment] 2019-02-10 18:13
@svitalsky While it is nice to add a link to a relevant StackExchange thread, it would be much easier to handle this if the issue would include actual information what the problem is, such that we do not have to reference an external site every time we look at this.

**Comment by zauguin** [comment] 2019-02-10 18:24
@u-fischer This seems to be a fontloader problem: I can reproduce it independant of the LuaTeX version and it is fixed by restoring the old fontloader.I do not have enough ConTeXt skills to create a ConTeXt example through, so can you send this to the ConTeXt list?

**Comment by zauguin** [comment] 2019-02-10 20:32
@svitalsky Could you test the fix in the PR? The easiest way would be to download [the modified version of luaotfload-letterspace.lua][patched] and saving it next to your document. Then compiling the document should use the new version.

[patched]: https://raw.githubusercontent.com/u-fischer/luaotfload/8a0260807bab2bf0234d052381f790cd422d7ac8/src/luaotfload-letterspace.lua

**Comment by svitalsky** [comment] 2019-02-10 21:03
@zauguin The fix seem to overcompensate (I mean visually, I have not the slightest idea what it does inside) the problem, letter spacing with it is now actually bigger then before the issue emerged.

**Comment by svitalsky** [comment] 2019-02-10 21:06
![luaotfload](https://user-images.githubusercontent.com/17103067/52539581-0d142a80-2d80-11e9-86e3-e9fffd54e201.png)

**Comment by svitalsky** [comment] 2019-02-10 21:06
(Space before “Some” is my mistake.)

**Comment by moewew** [comment] 2019-02-10 21:08
Sorry to barge in here, but since I provided the smaller example over on TeX.SX and tried to investigate a bit I hope you don't mind that.


With the fix the simplified MWE
```
\documentclass{article}

\usepackage{fontspec}
\setmainfont[LetterSpace = 150]{Latin Modern Roman}

\begin{document}
Some text with huge spacing
\end{document}
```
now compiles to the same result as XeLaTeX (which I find visually pleasing). With the older `v2.94ctan` (https://github.com/u-fischer/luaotfload/releases/tag/v2.94ctan) the result was different (the space between words was not spaced out resulting in a very squishy visual effect).

**Comment by u-fischer** [comment] 2019-02-10 21:09
@svitalsky  the letterspacing inside a word seems to be identical. What has changed (and we are just discussing) is that the space between words is now larger. But imho this is better, the old output was actually wrong and broken.

**Comment by svitalsky** [comment] 2019-02-10 21:11
@u-fischer I strongly disagree: **LetterSpacing** should **not** affect spaces between words.

**Comment by zauguin** [comment] 2019-02-10 21:16
@svitalsky At least for XeTeX and CSS letterspacing also affects interword space: The space is considered a letter and therefore both sides get some additional space.

**Comment by svitalsky** [comment] 2019-02-10 21:19
And I am not even mentioning (OK, now I am) how many documents such change in approach would break. In my case it's been thousands hours of work (well, actually I would just have to not update anymore) that you would now deliberately flush down the toilet.

**Comment by u-fischer** [comment] 2019-02-10 21:27
@svitalsky  xetex, pdftex (\letterspacefont) and microtype all stretch also the spaces. The behaviour of luaotfload has already for some time counted as inferior and slightly buggy, see e.g. https://tex.stackexchange.com/a/276445/2388. So please let us consider to correct this behaviour.

**Comment by zauguin** [comment] 2019-02-10 22:22
Regarding `microtype`: Before changing the behaviour of luaotfload, I think we should contact the `microtype` maintainer such that we can avoid both systems changing the interword space at the same time. If `microtype` is adjusted to deal with the new behaviour, we should have significantly less affected documents.

**Comment by zauguin** [comment] 2019-02-10 22:37
There are already two (undocumented?) global parameters to customize letterspacing: `letterspace.keepligatures` and `letterspace.keeptogether`. Especially `keeptogether` allows to set an arbitrary function which decides for every pair of characters if the letterspacing should be added.
We could either allow `.keeptogether` to also control letter spacing around glue or add a third parameter `letterspace.keepwordspacing` (or `.keepglue`) to fall back to the old behavior.
Then everyone can decide for themselves which behavior they prefer.

Of course this would leave us with another problem: What should be the default? On the one hand, not spacing around glue is compatible with older versions, on the other hand spacing around glue is compatible with XeTeX, pdfTeX etc. and seems more correct. So I think we should add enable letterspacing around glue by default, but document how to disable it in the changelog.

**Comment by u-fischer** [comment] 2019-02-10 22:57
`letterspace.keepwordspacing` sounds good. 

Imho the default behaviour should be the new one - I already complained years ago about the behaviour (https://github.com/lualatex/luaotfload/issues/297) and if it can at last be resolved it would be good. But we should compared the stretch of the word spacing with the one from xelatex. 

If you can write some small examples how to use the three options I will write the necessary documention (and make test files for the test suite). 

I doubt that there are many documents using both the microtype spacing and LetterSpace but I will write Robert so that he can check for problems. 

- but all not tonight ;-)

**Comment by zauguin** [comment] 2019-02-10 23:06
@u-fischer I already resolved the difference from XeLaTeX locally and will update the PR.

The microtype problem is not that someone might use microtype spacing and LetterSpace, it is that microtype implements letterspace through the luaotfload LetterSpace option (at least sometimes) but adds interword spacing.

But first I have to find some sleep...

**Comment by u-fischer** [comment] 2019-02-24 22:46
The issue will be resolved with version 2.96 which I'm just preparing for upload. 

As announced it will change the way spaces between words are handled. There is an option to revert this, check the documentation. The way ligatures are handled is changed too. By default ligatures stay. If you want to enable/disable ligatures in a letterspaced font, use the fontspec options.

**Closed by u-fischer** 2019-02-24 22:46 UTC

**Comment by simifilm** [comment] 2019-02-26 10:40
Version 2.96 seems to break `microtype`. Is this known?

**Comment by u-fischer** [comment] 2019-02-26 10:53
simifilm it shouldn't, but as we changed some letterspacing code, it could have side effects. Can you show an example?

**Comment by simifilm** [comment] 2019-02-26 10:57
> \documentclass[]{article}
> \usepackage{microtype}
> \begin{document}
> Haha
> \end{document}
> 

With `LuaLaTeX` this gives me the following:

> (/usr/local/texlive/2018/texmf-dist/tex/latex/microtype/microtype-luatex.def
> File: microtype-luatex.def 2018/01/14 v2.7a Definitions specific to luatex (RS)
> Lua module: microtype 2018/01/14 2.7a microtype module....exlive/2018/texmf-dist
> /tex/latex/microtype/microtype.lua:145: attempt to call field 'warning' (a nil v
> alue)
> stack traceback:
> 	...exlive/2018/texmf-dist/tex/latex/microtype/microtype.lua:145: in main chunk
> 	[C]: in function 'require'
> 	[\directlua]:1: in main chunk.
> l.59 \MT@lua{require("microtype")}
>                                 
> ? 

If I use the version of `luaotfload-letterspace.lua` post here, the MWE compiles smoothly.

**Comment by u-fischer** [comment] 2019-02-26 11:00
Ah. That's now our fault (or more precisely it is only a side-effect, microtype has a bug here). As a work-around add \usepackage{luatexbase}.  I will write Robert about it (forgot it last week ...)

**Comment by svitalsky** [comment] 2019-02-26 18:36
> As announced it will change the way spaces between words are handled. There is an option to revert this, check the documentation. 

@u-fischer Could you please be a bit more specific? Where is that option, where to put it (each document code, command line…), in what documentation…? I understand for you this area is something you know by heart and hence all this seems trivial, however it is not so for me and certainly others as well. I am not a TeX/Lua/… developer, and frankly with a change breaking so greatly many current documents you—even considering the fact of “open-sourceness” and its consequences—clearly owe your users some more detailed how-to. Thank you.

**Comment by zauguin** [comment] 2019-02-26 19:00
@svitalsky She meant the [regular `luaotfload` documentation](http://mirrors.ctan.org/macros/luatex/generic/luaotfload/luaotfload-latex.pdf), accessible through `texdoc luaotfload` if you installed TeXLive with documentation, by searching for `luaotfload` at [TeXdoc online](http://www.texdoc.net/) or on the [CTAN page](https://www.ctan.org/pkg/luaotfload) under the link "Package documentation".

Especially read page 10 and 11 for the letterspacing stuff.

**Comment by svitalsky** [comment] 2019-02-26 21:39
You are incredible, people: instead of one simple line: “put into each document `\directlua {luaotfload.letterspace.keepwordspacing = true}`” so many words, links and also more of my time wasted going through them till I've found that one line myself. I do NOT need to know this documentation, I might come to something like that anew perhaps in two or three or five years when someone breaks something again and I won't remember these links in that time.

Anyway, thanks.

**Comment by svitalsky** [comment] 2019-02-26 21:43
And to the point: the option mentioned above does not revert former behaviour completely. Without it, documents are broken completely, with it, there are some small differences here and there (perhaps 2 or 3 % of pages). I'll try to prepare some MWE, but probably not before weekend, I'll see.

**Comment by u-fischer** [comment] 2019-02-26 22:58
@svitalsky  We are maintaining this package for free in our spare time and we have any right to expect from you to check the documentation.  It is not our problem if you are not able to remember how to find the documentation.
